apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.15.1
    component: "client"
    heritage: Tiller
    release: wonderful-anteater
  name: wonderful-anteater-elasticsearch-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.15.1
    component: "data"
    heritage: Tiller
    release: wonderful-anteater
  name: wonderful-anteater-elasticsearch-data
---
# Source: elasticsearch/templates/master-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.15.1
    component: "master"
    heritage: Tiller
    release: wonderful-anteater
  name: wonderful-anteater-elasticsearch-master