apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: elasticsearch-client
  name: elasticsearch-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: elasticsearch-data
  name: elasticsearch-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: elasticsearch-master
  name: elasticsearch-master