# Source: elasticsearch/templates/client-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-client
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: elasticsearch-client
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: elasticsearch-client
  type: ClusterIP
---
# master节点的服务端口
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: elasticsearch
  name: elasticsearch-discovery
spec:
  clusterIP: None
  ports:
    - port: 9300
      protocol: TCP
      targetPort: transport
  publishNotReadyAddresses: true # 不知道这个配置干啥的？？？
  sessionAffinity: None # 不知道这个配置干啥的？？？
  selector:
    app: elasticsearch-master