apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: kafka
  name: kafka
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: node-reader
subjects:
- kind: ServiceAccount
  name: kafka
  namespace: {{ $.Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: node-reader