apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pv-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rook-ceph-demo
spec:
  template:
    metadata:
      labels:
        app: rook-ceph-demo
    spec:
      containers:
      - name: rook-ceph-demo
        image: rg-bigdata/rg-base:0.0.1
        command: ['sleep', '1d']
        volumeMounts:
        - name: persistent-storage
          mountPath: /mnt
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ceph-pv-claim
